### ISSUE TITLE
2022 Release

### ISSUE THREAD

**Issue by calum-chamberlain** [calum-chamberlain/ESCI451-Python#19]
Before the start of term we need to:
- [x] Finalise notebooks and environment.yml (#18 should be the final PR)
- [x] Set up env on SGEES computers - *Aleks is working on this now*
- [x] Upload environment.yml and instructions to Blackboard - *I will wait until @jtownendVUW has BB set up with folders etc.*
- [x] Clean notebooks (remove all output) *done in 2022_release branch*
- [x] Check binder works - *works, but interactive plotting doesn't - will need to use `%matplotlib inline` on binder.*
- [x] Create release of clean notebooks - *clean release is here [2022.0.2](https://github.com/calum-chamberlain/ESCI451-Python/archive/refs/tags/2022.0.2.zip)*
- [x] Upload notebooks to blackboard
- [x] Get students to set up the env on their machines

**Comment by trap000d** [comment]
Another dependency hell has been introduced in recent ipython version: https://github.com/ipython/ipython/issues/13463
Effectively environment can't be created. Override is to add ```black``` to dependency list in environment.yml

**Comment by calum-chamberlain** [comment]
Ugh, I wondered why my ipython was changing my text! However, I have been able to create the environment on multiple machines - what is the issue with creating the environment as it stands?

**Comment by trap000d** [comment]
If recent ipython [>=8.0] (and, effectively, black) is already installed (either system-wide, or as part of base conda environment), then all goes well. Otherwise conda crashes on ipython installation. There is no system-wide ipython on our workstations in co-501, that's why I've caught the bug.

**Comment by calum-chamberlain** [comment]
Ah, that is annoying. I will add black to the dependencies then and make a new release. Thanks for catching this.
