### ISSUE TITLE
Error in caluclating displacement in module 4B

### ISSUE THREAD

**Issue by calum-chamberlain** [calum-chamberlain/ESCI451-Python#26]
The code that gets works out the displacement is wrong in module 4B - it ends up subtracting between the indices of the dataframe, not the values. the code should be changed to something like:
```python
date_filter = (GNSS_data['time'] >= '2016/11/06T11:02:56') & (
    GNSS_data['time'] <= '2016/11/20T11:02:56')

N_first_value = GNSS_data.loc[date_filter]['north'].to_numpy()[0]
N_last_value = GNSS_data.loc[date_filter]['north'].to_numpy()[-1]

N_disp = N_last_value - N_first_value

print(f"The displacement is {N_disp} mm")
```
The text beforehand describing the handy index methods should be changed to match this code as well.

**Comment by FinniganIK** [comment]
Or something like:
```
FirstIndex = GNSS_data.loc[date_filter]['north'].first_valid_index()
FirstValue = GNSS_data['north'][FirstIndex]
```

**Comment by FinniganIK** [comment]
And then make sure this is working correctly in the vector dataframe
