### ISSUE TITLE
Is seaborn helpful?

### ISSUE THREAD

**Issue by FinniganIK** [calum-chamberlain/ESCI451-Python#29]
Last year I added some seaborn exercises in module 3B. In retrospect I'm not convinced this is useful. It's designed to be a little bit black box-like and there have been a few students who have used it since and have been frustrated at trying to make minor formatting changes to seaborn plot, which is not what it's designed for and isn't straightforward

**Comment by calum-chamberlain** [comment]
If it hasn't helped students and we can do it another way, then I would be keen to remove it. Or, we could include notes on how to make some of those formatting changes - do you remember any of the formatting changes that were difficult?

**Comment by calum-chamberlain** [comment]
I still like it now that I'm going through, and have added some notes on customising some elements of the plots.
