### ISSUE TITLE
Things to add in 2022

### ISSUE THREAD

**Issue by FinniganIK** [calum-chamberlain/ESCI451-Python#8]
- [ ] Plot focal mechanisms from John Ristau's GeoNet dataset: https://github.com/GeoNet/data/tree/main/moment-tensor
- [x] Plot vectors (calculated from GPS timeseries?)
- [x] Inset maps

**Comment by FinniganIK** [comment]
Not sure that plotting focal mechanisms is actually a good idea. A large % of students might not know what a focal mechanism is

**Comment by calum-chamberlain** [comment]
They *should* know from ESCI203, but I think that you are right that many of them either won't know, or won't remember. Agree that the focus should be on the coding, rather than having to explain the maps!
